/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedDataTable: typeof import('./src/components/table/AdvancedDataTable.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    PageHeader: typeof import('./src/components/ui/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableConfigPanel: typeof import('./src/components/table/TableConfigPanel.vue')['default']
    UserForm: typeof import('./src/components/form/UserForm.vue')['default']
    ViewManager: typeof import('./src/components/view/ViewManager.vue')['default']
  }
}
